// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

namespace backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190411163907_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("backend.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.HasKey("Id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("backend.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FromWhere");

                    b.Property<DateTime>("endDate");

                    b.Property<string>("guestName");

                    b.Property<string>("guestSurname");

                    b.Property<int>("placeId");

                    b.Property<DateTime>("startDate");

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("backend.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("employeeId");

                    b.Property<int>("guestId");

                    b.Property<string>("officeName");

                    b.Property<string>("officeNumber");

                    b.HasKey("Id");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("backend.Models.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsColor");

                    b.Property<int>("Number");

                    b.HasKey("Id");

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("backend.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<bool>("IsBlackboard");

                    b.Property<bool>("IsPhone");

                    b.Property<bool>("IsTV");

                    b.Property<int>("NumberOfPeople");

                    b.Property<string>("roomName");

                    b.Property<string>("roomNumber");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
